name: Puppeteer & Lighthouse 

on:
  workflow_run:
    workflows: ["Deploy Next.js site to Pages"]
    types:
      - completed

jobs:
  run-script:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Script
        run: node scripts/main.mjs

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: script-artifacts
          path: auto_* 
